title: "🏰 Kremlin"
theme: dark
color: slate
background: 
  image: images/background.jpg

  blur: sm

  brightness: 45

  opacity: 35
headerStyle: clean
layout:
  - Infrastructure:
      style: row
      columns: 4
  - Media:
      style: row
      columns: 4
  - Automation:
      style: row
      columns: 4
  - Tools:
      style: row
      columns: 4
cardBlur: xl
showStats: true
statusStyle: "dot"
hideVersion: true
#footer:
#  hide: true
#favicon: https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/homepage.svg
