---
addic7ed:
  cookies: ''
  password: ''
  user_agent: ''
  username: ''
  vip: false
analytics:
  enabled: true
anidb:
  api_client: ''
  api_client_ver: 1
animetosho:
  anidb_api_client: ''
  anidb_api_client_ver: 1
  search_threshold: 6
anticaptcha:
  anti_captcha_key: ''
assrt:
  token: ''
auth:
  apikey: a46319df17060c92fb052978abc7c0bd
  password: ''
  type: null
  username: ''
avistaz:
  cookies: ''
  user_agent: ''
backup:
  day: 6
  folder: /config/backup
  frequency: Weekly
  hour: 3
  retention: 31
betaseries:
  token: ''
captchaai:
  captchaai_key: ''
cinemaz:
  cookies: ''
  user_agent: ''
cors:
  enabled: false
deathbycaptcha:
  password: ''
  username: ''
embeddedsubtitles:
  fallback_lang: en
  hi_fallback: false
  included_codecs: []
  timeout: 600
  unknown_as_fallback: false
general:
  adaptive_searching: true
  adaptive_searching_delay: 3w
  adaptive_searching_delta: 1w
  anti_captcha_provider: null
  auto_update: true
  base_url: ''
  branch: master
  chmod: '0640'
  chmod_enabled: false
  concurrent_jobs: 4
  days_to_upgrade_subs: 7
  debug: false
  default_und_audio_lang: ''
  default_und_embedded_subtitles_lang: ''
  disable_all_providers_ssl_verify: false
  dont_notify_manual_actions: false
  embedded_subs_show_desired: true
  embedded_subtitles_parser: ffprobe
  enable_strm_support: false
  enabled_integrations: []
  enabled_providers:
  - opensubtitlescom
  external_webhook_password: ''
  external_webhook_url: ''
  external_webhook_username: ''
  flask_secret_key: 40faffdb49a8a711dd54d0c6354daa9c
  hi_extension: hi
  hostname: 3b0e1e87659a
  ignore_ass_subs: false
  ignore_pgs_subs: false
  ignore_vobsub_subs: false
  instance_name: Bazarr
  ip: '*'
  language_equals: []
  minimum_score: 90
  minimum_score_movie: 70
  movie_default_enabled: true
  movie_default_profile: 1
  movie_tag_enabled: true
  multithreading: true
  notify_if_nothing_is_missing_for_signalr_event: false
  page_size: 25
  parse_embedded_audio_track: false
  path_mappings: []
  path_mappings_movie: []
  port: 6767
  postprocessing_cmd: ''
  postprocessing_threshold: 90
  postprocessing_threshold_movie: 70
  remove_profile_tags: []
  serie_default_enabled: true
  serie_default_profile: 1
  serie_tag_enabled: true
  show_live_badge: true
  single_language: false
  skip_hashing: false
  subfolder: current
  subfolder_custom: ''
  subzero_mods: ''
  theme: auto
  upgrade_frequency: 12
  upgrade_manual: true
  upgrade_subs: true
  use_embedded_subs: true
  use_external_webhook: false
  use_jellyfin: true
  use_plex: false
  use_postprocessing: false
  use_postprocessing_threshold: false
  use_postprocessing_threshold_movie: false
  use_radarr: true
  use_scenename: true
  use_sonarr: true
  use_whisper_fallback: false
  use_whisper_fallback_series: false
  utf8_encode: true
  wanted_search_frequency: 6
  wanted_search_frequency_movie: 6
hdbits:
  passkey: ''
  username: ''
jellyfin:
  apikey: 65edcbd299014fb2a7b0c3283da5ca76
  movie_library:
  - Filmes
  movie_library_ids:
  - af92f2d68eea947c7f9df41836afb987
  refresh_method: immediate
  series_library:
  - "S\xE9ries"
  series_library_ids:
  - d565273fd114d77bdf349a2896867069
  update_movie_library: false
  update_series_library: false
  url: http://192.168.68.52:8096
jimaku:
  api_key: ''
  enable_ai_subs: false
  enable_archives_download: false
  enable_name_search_fallback: true
karagarga:
  f_password: ''
  f_username: ''
  password: ''
  username: ''
ktuvit:
  email: ''
  hashed_password: ''
legendasdivx:
  password: ''
  skip_wrong_fps: false
  username: ''
legendasnet:
  password: ''
  username: ''
log:
  exclude_filter: ''
  ignore_case: false
  include_filter: ''
  use_regex: false
napiprojekt:
  only_authors: false
  only_real_names: false
napisy24:
  password: ''
  username: ''
opensubtitlescom:
  include_ai_translated: false
  include_machine_translated: false
  password: '#*sQjJOH0!o&wpX'
  use_hash: true
  username: khrusko
pipocas:
  password: ''
  username: ''
plex:
  apikey: ''
  auth_method: apikey
  client_identifier: ''
  disable_auto_migration: false
  email: ''
  encryption_key: TkgO_kyKWNWlDgiMb4PJju7B3Rljbtu2_VI-PMZT9ew
  ip: 127.0.0.1
  migration_attempted: false
  migration_successful: false
  migration_timestamp: ''
  movie_library: []
  movie_library_ids: []
  port: 32400
  series_library: []
  series_library_ids: []
  server_local: false
  server_machine_id: ''
  server_name: ''
  server_url: ''
  set_episode_added: false
  set_movie_added: false
  ssl: false
  token: ''
  update_movie_library: false
  update_series_library: false
  user_id: ''
  username: ''
postgresql:
  database: ''
  enabled: false
  host: localhost
  password: ''
  port: 5432
  url: ''
  username: ''
proxy:
  exclude:
  - localhost
  - 127.0.0.1
  password: ''
  port: ''
  type: null
  url: ''
  username: ''
radarr:
  apikey: a97d2b3876e940c7a357196cb57de293
  base_url: ''
  defer_search_signalr: false
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 4
  http_timeout: 60
  ip: 192.168.68.52
  movies_sync: 60
  movies_sync_on_live: true
  only_monitored: false
  port: 7878
  ssl: false
  sync_only_monitored_movies: false
  use_ffprobe_cache: true
sonarr:
  apikey: 027795c9b07b4d109d65987b5bc01ab1
  base_url: ''
  defer_search_signalr: false
  exclude_season_zero: false
  excluded_series_types: []
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 4
  http_timeout: 60
  ip: 192.168.68.52
  only_monitored: false
  port: 8989
  series_sync: 60
  series_sync_on_live: true
  ssl: false
  sync_only_monitored_episodes: false
  sync_only_monitored_series: false
  use_ffprobe_cache: true
subdl:
  api_key: ''
subf2m:
  user_agent: ''
  verify_ssl: true
subsarr:
  base_url: ''
subsource:
  apikey: ''
subsro:
  api_key: ''
subsync:
  auto_use_original_language: false
  checker:
    blacklisted_languages: []
    blacklisted_providers: []
  debug: false
  force_audio: false
  gss: true
  max_offset_seconds: 60
  no_fix_framerate: true
  subsync_movie_threshold: 70
  subsync_threshold: 90
  use_original_language: false
  use_subsync: true
  use_subsync_movie_threshold: false
  use_subsync_threshold: false
subx:
  api_key: ''
titlovi:
  password: ''
  username: ''
titulky:
  approved_only: false
  password: ''
  skip_wrong_fps: false
  username: ''
translator:
  default_score: 50
  gemini_batch_size: 300
  gemini_keys: []
  gemini_model: gemini-2.0-flash
  lingarr_token: ''
  lingarr_url: http://lingarr:9876
  translator_info: true
  translator_type: google_translate
turkcealtyaziorg:
  cookies: ''
  user_agent: ''
whisperai:
  endpoint: http://127.0.0.1:9000
  loglevel: INFO
  pass_video_name: false
  response: 5
  timeout: 3600
xsubs:
  password: ''
  username: ''
