services:
  netdata:
    image: netdata/netdata:v2.2.3
    container_name: netdata
    hostname: netdata-monitor
    restart: unless-stopped
    pid: host
    ports:
      - "19999:19999"
    volumes:
      - ./netdata/etc:/etc/netdata:rw
      - ./netdata/var:/var/lib/netdata:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /proc:/proc:rw
      - /sys:/sys:rw
      - /etc/os-release:/etc/os-release:rw
      - /var/log:/var/log:rw
    environment:
      - NETDATA_DISABLE_CLOUD=1
      - NETDATA_DISABLE_TELEMETRY=1
      - NETDATA_ADD_DOCKER_SOCKET_READONLY=1
      - TZ=America/Sao_Paulo
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    networks:
      - homelab-net

networks:
  homelab-net:
    external: true
    name: homelab_homelab-net